# version format
version: 1.0.{build}

branches:
  # whitelist
  only:
    - master
    
skip_tags: true

environment:
  # See README for information on the token
  binstar_token:
    secure: va2cH3651uru58ThstGxm6R/Rvjw4xC13WnQFQpP0bgc8IjYrbBJWLLMvrCuSgWF

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\continuous-integration\\appveyor\\run_with_env.cmd"

  matrix:
  
    - PYTHON: "C:\\Python34_32"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"
      CONDA_PY: "34"
      CONDA_NPY: "18"

    - PYTHON: "C:\\Python34_64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"
      CONDA_PY: "34"
      CONDA_NPY: "18"
      
install:
  # install TensorFlow (CPU version).
  - pip install tensorflow
  - pip install scikit-learn
  - pip  install keras
  
  # install pydot for visualization tests
  - conda install pydot graphviz

# command to run tests
test_script:
  python HDLTex/HDLTex.py;
